version: "3"

tasks:
  build:
    desc: Build git-helper for all arches and OSes
    cmds:
      - task: build:darwin:arm64

  build:darwin:arm64:
    desc: Build git-helper for darwin arm64
    cmds:
      - cmd: GOOS=darwin GOARCH=arm64 go build -o git-helper_darwin_arm64

  build:test:
    desc: Build go-git-helper for testing purposes
    cmds:
      - cmd: GOOS=darwin GOARCH=arm64 go build -o go-git-helper
      - cmd: sudo mv go-git-helper /usr/local/bin/go-git-helper
