package codeRequest

import (
	"os"
	"path/filepath"
	"testing"
)

type MockExecutor struct {
	Args    []string
	Command string
	Debug   bool
	Output  []byte
}

func (me *MockExecutor) Exec(execType string, command string, args ...string) ([]byte, error) {
	me.Command = command
	me.Args = args
	return me.Output, nil
}

func setupTestConfig(t *testing.T) func() {
	homeDir, err := os.UserHomeDir()
	if err != nil {
		t.Fatal(err)
	}

	configDir := filepath.Join(homeDir, ".git-helper")
	configFile := filepath.Join(configDir, "config.yml")

	// Check if config already exists
	existingConfig, _ := os.ReadFile(configFile)

	// Create test config with special capitalization
	testConfig := `github_username: test_user
github_token: test_token
special_capitalization:
  api: API
  aws: AWS
  cd: CD
  cdn: CDN
  ci: CI
  css: CSS
  csv: CSV
  dns: DNS
  docker: Docker
  e2e: E2E
  ec2: EC2
  eslint: ESLint
  gcp: GCP
  gh: GH
  github: GitHub
  gitlab: GitLab
  gl: GL
  go: Go
  golang: Golang
  google: Google
  graphql: GraphQL
  grpc: gRPC
  html: HTML
  http: HTTP
  https: HTTPS
  id: ID
  ios: iOS
  ipv4: IPv4
  ipv6: IPv6
  javascript: JavaScript
  jenkins: Jenkins
  js: JS
  json: JSON
  jwt: JWT
  k8s: K8s
  kubernetes: Kubernetes
  lambda: Lambda
  macos: macOS
  mongodb: MongoDB
  mr: MR
  mysql: MySQL
  nextjs: Next.js
  nginx: NGINX
  nodejs: Node.js
  nosql: NoSQL
  oauth: OAuth
  pdf: PDF
  postgres: PostgreSQL
  postgresql: PostgreSQL
  pr: PR
  prettier: Prettier
  qa: QA
  react: React
  reactjs: React
  rds: RDS
  redis: Redis
  rest: REST
  route53: Route53
  s3: S3
  saml: SAML
  sql: SQL
  ssl: SSL
  sso: SSO
  terraform: Terraform
  tls: TLS
  ts: TS
  typescript: TypeScript
  ui: UI
  uri: URI
  url: URL
  ux: UX
  vue: Vue.js
  vuejs: Vue.js
  vpc: VPC
  websocket: WebSocket
  websockets: WebSockets
  xml: XML
  yaml: YAML
`

	// Create config directory if it doesn't exist
	os.MkdirAll(configDir, 0755)

	// Write test config
	err = os.WriteFile(configFile, []byte(testConfig), 0644)
	if err != nil {
		t.Fatal(err)
	}

	// Return cleanup function
	return func() {
		if len(existingConfig) > 0 {
			// Restore original config
			os.WriteFile(configFile, existingConfig, 0644)
		} else {
			// Remove test config if there wasn't one before
			os.Remove(configFile)
		}
	}
}

func Test_autogeneratedTitle(t *testing.T) {
	cleanup := setupTestConfig(t)
	defer cleanup()

	tests := []struct {
		name           string
		executorOutput []byte
		expected       string
	}{
		{
			name:           "regular branch",
			executorOutput: []byte("* feature-branch"),
			expected:       "Feature branch",
		},
		{
			name:           "single word branch",
			executorOutput: []byte("* feature"),
			expected:       "Feature",
		},
		{
			name:           "Jira branch with underscores",
			executorOutput: []byte("* jira_123_something"),
			expected:       "JIRA-123 Something",
		},
		{
			name:           "Jira branch with dashes",
			executorOutput: []byte("* jira-123-something"),
			expected:       "JIRA-123 Something",
		},
		{
			name:           "Jira branch with combo 1",
			executorOutput: []byte("* jira-123_something"),
			expected:       "JIRA-123 Something",
		},
		{
			name:           "Jira branch with combo 2",
			executorOutput: []byte("* jira_123-something-else"),
			expected:       "JIRA-123 Something else",
		},
		{
			name:           "Jira branch with combo 3",
			executorOutput: []byte("* jira-29142"),
			expected:       "JIRA-29142",
		},
		{
			name:           "Branch with AWS",
			executorOutput: []byte("* feature-aws-deployment"),
			expected:       "Feature AWS deployment",
		},
		{
			name:           "Branch with GitHub",
			executorOutput: []byte("* update-github-integration"),
			expected:       "Update GitHub integration",
		},
		{
			name:           "Branch with multiple special words",
			executorOutput: []byte("* aws-api-gateway-setup"),
			expected:       "AWS API gateway setup",
		},
		{
			name:           "Jira branch with special words",
			executorOutput: []byte("* jira_123_aws_api_update"),
			expected:       "JIRA-123 AWS API update",
		},
	}

	for _, test := range tests {
		executor := &MockExecutor{
			Debug:  true,
			Output: test.executorOutput,
		}

		cr := newCodeRequest(true, executor)
		resp := cr.autogeneratedTitle()

		if resp != test.expected {
			t.Fatalf(`expected %v, but got %v`, test.expected, resp)
		}
	}
}

func Test_checkAllLetters(t *testing.T) {
	executor := &MockExecutor{Debug: true}
	cr := newCodeRequest(true, executor)
	resp := cr.checkAllLetters("iekslkjasd")

	if resp == false {
		t.Fatalf(`string %v should be all letters`, resp)
	}

	resp = cr.checkAllLetters("iekslkjasd321")

	if resp == true {
		t.Fatalf(`string %v should not be all letters`, resp)
	}
}

func Test_checkAllNumbers(t *testing.T) {
	executor := &MockExecutor{Debug: true}
	cr := newCodeRequest(true, executor)
	resp := cr.checkAllNumbers("284161")

	if resp == false {
		t.Fatalf(`string %v should be all numbers`, resp)
	}

	resp = cr.checkAllNumbers("39812k3jiksd9z")

	if resp == true {
		t.Fatalf(`string %v should not be all numbers`, resp)
	}
}

func Test_matchesFullJiraPattern(t *testing.T) {
	executor := &MockExecutor{Debug: true}
	cr := newCodeRequest(true, executor)
	resp := cr.matchesFullJiraPattern("jira-29142")

	if resp == false {
		t.Fatalf(`string %v should match Jira pattern (e.g. jira-123)`, resp)
	}

	resp = cr.matchesFullJiraPattern("jIra*3291")

	if resp == true {
		t.Fatalf(`string %v should not match Jira pattern (e.g. jira-123)`, resp)
	}
}

func Test_titleize(t *testing.T) {
	executor := &MockExecutor{Debug: true}
	cr := newCodeRequest(true, executor)
	resp := cr.titleize("mysTrInG")

	if resp != "MysTrInG" {
		t.Fatalf(`string %v was not properly titleized`, resp)
	}
}

func Test_isGitHub(t *testing.T) {
	tests := []struct {
		remotes  string
		expected bool
	}{
		{
			remotes: `origin  git@github.com:emmahsax/go-git-helper.git (fetch)
origin  git@github.com:emmahsax/go-git-helper.git (push)`,
			expected: true,
		},
		{
			remotes: `origin  git@gitlab.com:emmahsax/github-project.git (fetch)
origin  git@gitlab.com:emmahsax/github-project.git (push)`,
			expected: false,
		},
	}

	for _, test := range tests {
		executor := &MockExecutor{
			Debug:  true,
			Output: []byte(test.remotes),
		}
		cr := newCodeRequest(true, executor)
		resp := cr.isGitHub()

		if resp != test.expected {
			t.Fatalf(`should have been %v, but was %v`, test.expected, resp)
		}
	}
}

func Test_isGitLab(t *testing.T) {
	tests := []struct {
		remotes  string
		expected bool
	}{
		{
			remotes: `origin  git@gitlab.com:emmahsax/go-git-helper.git (fetch)
origin  git@gitlab.com:emmahsax/go-git-helper.git (push)`,
			expected: true,
		},
		{
			remotes: `origin  git@github.com:emmahsax/gitlab-project.git (fetch)
origin  git@github.com:emmahsax/gitlab-project.git (push)`,
			expected: false,
		},
	}

	for _, test := range tests {
		executor := &MockExecutor{
			Debug:  true,
			Output: []byte(test.remotes),
		}
		cr := newCodeRequest(true, executor)
		resp := cr.isGitLab()

		if resp != test.expected {
			t.Fatalf(`should have been %v, but was %v`, test.expected, resp)
		}
	}
}

func Test_containsSubstring(t *testing.T) {
	executor := &MockExecutor{Debug: true}
	cr := newCodeRequest(true, executor)
	strs := []string{"string1", "string3", "string18"}
	resp := cr.containsSubstring(strs, "string3")

	if resp == false {
		t.Fatalf(`string %v should be present in %v`, "string3", strs)
	}

	resp = cr.containsSubstring(strs, "string2")

	if resp == true {
		t.Fatalf(`string %v should not be present in %v`, "string2", strs)
	}
}

func Test_applySpecialCapitalization(t *testing.T) {
	cleanup := setupTestConfig(t)
	defer cleanup()

	tests := []struct {
		name     string
		input    string
		expected string
	}{
		{
			name:     "AWS in title",
			input:    "Deploy to aws",
			expected: "Deploy to AWS",
		},
		{
			name:     "GitHub in title",
			input:    "Fix github integration",
			expected: "Fix GitHub integration",
		},
		{
			name:     "Multiple special words",
			input:    "Update aws and gcp configs",
			expected: "Update AWS and GCP configs",
		},
		{
			name:     "Special words with hyphens",
			input:    "Deploy-to-aws-via-github",
			expected: "Deploy-to-AWS-via-GitHub",
		},
		{
			name:     "Special words with underscores",
			input:    "Update_gh_api_integration",
			expected: "Update_GH_API_integration",
		},
		{
			name:     "Special words with slashes",
			input:    "Update/aws/config",
			expected: "Update/AWS/config",
		},
		{
			name:     "Mixed case input",
			input:    "Deploy to AwS",
			expected: "Deploy to AWS",
		},
		{
			name:     "No special words",
			input:    "Regular feature branch",
			expected: "Regular feature branch",
		},
		{
			name:     "API and UI",
			input:    "Update api ui components",
			expected: "Update API UI components",
		},
		{
			name:     "GraphQL and REST",
			input:    "Add graphql and rest endpoints",
			expected: "Add GraphQL and REST endpoints",
		},
		{
			name:     "Docker and Kubernetes",
			input:    "Setup docker and kubernetes deployment",
			expected: "Setup Docker and Kubernetes deployment",
		},
		{
			name:     "Node.js and TypeScript",
			input:    "Migrate to nodejs and typescript",
			expected: "Migrate to Node.js and TypeScript",
		},
		{
			name:     "AWS services",
			input:    "Configure s3 ec2 and route53",
			expected: "Configure S3 EC2 and Route53",
		},
		{
			name:     "iOS and macOS",
			input:    "Update ios and macos support",
			expected: "Update iOS and macOS support",
		},
		{
			name:     "Database names",
			input:    "Add mysql mongodb and redis support",
			expected: "Add MySQL MongoDB and Redis support",
		},
		{
			name:     "SSL and TLS",
			input:    "Enable ssl and tls encryption",
			expected: "Enable SSL and TLS encryption",
		},
		{
			name:     "CI/CD pipeline",
			input:    "Setup ci/cd pipeline",
			expected: "Setup CI/CD pipeline",
		},
	}

	executor := &MockExecutor{Debug: true}
	cr := newCodeRequest(true, executor)

	for _, test := range tests {
		t.Run(test.name, func(t *testing.T) {
			resp := cr.applySpecialCapitalization(test.input)
			if resp != test.expected {
				t.Fatalf(`expected %v, but got %v`, test.expected, resp)
			}
		})
	}
}

func Test_applySpecialCapitalization_noConfig(t *testing.T) {
	homeDir, err := os.UserHomeDir()
	if err != nil {
		t.Fatal(err)
	}

	configDir := filepath.Join(homeDir, ".git-helper")
	configFile := filepath.Join(configDir, "config.yml")

	// Save existing config if present
	existingConfig, _ := os.ReadFile(configFile)

	// Remove config file to test no-config behavior
	os.Remove(configFile)

	// Restore config after test
	defer func() {
		if len(existingConfig) > 0 {
			os.WriteFile(configFile, existingConfig, 0644)
		}
	}()

	tests := []struct {
		name     string
		input    string
		expected string
	}{
		{
			name:     "No config - AWS stays lowercase",
			input:    "Deploy to aws",
			expected: "Deploy to aws",
		},
		{
			name:     "No config - GitHub stays as is",
			input:    "Fix github integration",
			expected: "Fix github integration",
		},
		{
			name:     "No config - multiple words unchanged",
			input:    "Update aws and gcp configs",
			expected: "Update aws and gcp configs",
		},
		{
			name:     "No config - CI/CD unchanged",
			input:    "Setup ci/cd pipeline",
			expected: "Setup ci/cd pipeline",
		},
	}

	executor := &MockExecutor{Debug: true}
	cr := newCodeRequest(true, executor)

	for _, test := range tests {
		t.Run(test.name, func(t *testing.T) {
			resp := cr.applySpecialCapitalization(test.input)
			if resp != test.expected {
				t.Fatalf(`expected %v, but got %v`, test.expected, resp)
			}
		})
	}
}
