name: Release
run-name: Release ${{ inputs.tag_name }}

on:
  workflow_dispatch:
    inputs:
      tag_name:
        description: The tag name to make a GitHub Release for
        required: true
        type: string

jobs:
  go-release:
    if: github.ref == 'refs/heads/main'
    uses: emmahsax/github-actions/.github/workflows/go-release.yml@main
    with:
      build_command: task build
      files: |
        git-helper_darwin_arm64
      go_version: 1.24
      tag_name: ${{ inputs.tag_name }}
      upload: true
