name: Version Bump Check

on:
  pull_request:

jobs:
  version-bump-check:
    uses: emmahsax/github-actions/.github/workflows/version-bump-check.yml@main
    with:
      description: version update
      file: main.go
      regex: \s+packageVersion\s+=\s+"\S+"
